import localFont from 'next/font/local';

import { Providers } from './providers';

import type { Metadata } from 'next';

import './globals.css';
import ServiceWorkerRegistration from '@/components/(alert)/ServiceWorkerRegistration';
import TrackingLayout from '@/components/(layout)/tracking-layout';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Ginet Billiard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TrackingLayout>
      <html lang="en">
        <Providers>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <main>{children}</main>
            <ServiceWorkerRegistration />
          </body>
        </Providers>
      </html>
    </TrackingLayout>
  );
}
