import localFont from 'next/font/local';
import Nav from '@/components/(layout)/nav';
import Footer from '@/components/(layout)/footer';

import { Providers } from './providers';
import { NotificationProvider } from '@/components/(provider)/notification-context';
import ServiceWorkerRegistration from '@/components/(alert)/service-worker-registration';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Ginet Billiard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Nav />
          <NotificationProvider>
            <main>{children}</main>
            <ServiceWorkerRegistration />
          </NotificationProvider>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
